-- file auto generated by Grit Editor, be careful when modifying this manually
-- this file stores all editor configurations.

editor_cfg = {
  directory        = "editor";
  load_startup_map = true;
  maps_dir         = "../maps";
  mode_selected    = "rotate";
  startup_map      = "/editor/core/defaultmap/defaultmap.lvl";
  thumbnails_size  = vector2(256, 256);
}