-- file auto generated by Grit Editor, be careful when modifying this manually
-- this file stores all editor interface configuration, like frames size, positions,
-- interface customizations, etc.

-- TODO
editor_interface_cfg = {
	content_browser = { opened = false, position={500, 680}, size={800, 650} };
	graph_editor = { opened = false, position={20, 150}, size={500, 400} };
	object_properties = { opened = false, position={1000, 800}, size={300, 500} };
	object_editor = { opened = false, position={1000, 800}, size={300, 500} };
	material_editor = { opened = false, position={1000, 800}, size={300, 500} };
	level_properties = { opened = false, position={1000, 800}, size={300, 500} };
	outliner = { opened = false, position={1000, 800}, size={300, 500} };
	settings = { opened = false, position={1000, 800}, size={300, 500} };
	size={1650, 900};
	position={250, 250};
	theme="dark_orange";
}