-- file auto generated by Grit Editor, be careful when modifying this manually
-- this file stores all editor interface configuration, like windows sizes, positions,
-- interface customizations, etc.

editor_interface_cfg = {
  content_browser   =   {
    opened   = false;
    position = { 22, 10 };
    size     = { 640, 365 };
  };
  event_editor      =   {
    opened   = false;
    position = { -136, -231 };
    size     = { 608, 200 };
  };
  level_properties  =   {
    opened   = false;
    position = { 236.5, -240 };
    size     = { 449, 225 };
  };
  material_editor   =   {
    opened   = false;
    position = { -3, -5 };
    size     = { 512, 200 };
  };
  object_editor     =   {
    opened   = false;
    position = { -148, 19 };
    size     = { 350, 200 };
  };
  object_properties =   {
    opened   = false;
    position = { -158.5, -99 };
    size     = { 353, 426 };
  };
  outliner          =   {
    opened   = false;
    position = { 0, 0 };
    size     = { 540, 400 };
  };
  settings          =   {
    opened   = false;
    position = { -11.5, -174 };
    size     = { 611, 200 };
  };
  size              = { 1024, 768 };
  theme             = "dark_orange";
}