-- file auto generated by Grit Editor, be careful when modifying this manually
-- this file stores recently opened maps

-- TODO
recent = {
	["Entry"] = "/maps/entry.lvl";
	["Playground"] = "/maps/playground.lvl";
}