-- file auto generated by Grit Editor, be careful when modifying this manually
-- this file stores all editor configurations

editor_cfg = {
    maps_dir = "../maps";
    thumbnails_size = vec2(256, 256);
    mode_selected = "translate";
    directory = "./editor";
    load_startup_map = false;
    startup_map = `default_map/defaultmap.gmap`;
    default_game_mode = "First Person";
    step_size = 0.1;
}
