-- file auto generated by Grit Editor, be careful when modifying this manually
-- this file stores all Grit Editor interface configuration, like windows sizes, positions,
-- interface customizations, etc.

editor_interface_cfg = {
  content_browser   =   {
    opened   = false;
    position = { 0, 0 };
    size     = { 640, 400 };
  };
  level_properties  =   {
    opened   = false;
    position = { 0, 0 };
    size     = { 380, 225 };
  };
  material_editor   =   {
    opened   = false;
    position = { 0, 0 };
    size     = { 540, 400 };
  };
  object_editor     =   {
    opened   = false;
    position = { 0, 0 };
    size     = { 540, 400 };
  };
  object_properties =   {
    opened   = false;
    position = { 0, 0 };
    size     = { 540, 400 };
  };
  outliner          =   {
    opened   = false;
    position = { 0, 0 };
    size     = { 540, 400 };
  };
  settings          =   {
    opened   = false;
    position = { 0, 0 };
    size     = { 350, 200 };
  };
  size              = { 1280, 720 };
  theme             = "dark";
}
