# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = obj/Debug/RecastDetour
  TARGETDIR  = lib/Debug
  TARGET     = $(TARGETDIR)/libRecastDetour.a
  DEFINES   += -DDEBUG
  INCLUDES  += -IDebugUtils/Include -IDetour/Include -IDetourTileCache/Include -IDetourCrowd/Include -IRecast/Include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -Wall -ffast-math -g
  CXXFLAGS  += $(CFLAGS) -fno-exceptions -fno-rtti
  LDFLAGS   += 
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = obj/Release/RecastDetour
  TARGETDIR  = lib/Release
  TARGET     = $(TARGETDIR)/libRecastDetour.a
  DEFINES   += -DNDEBUG
  INCLUDES  += -IDebugUtils/Include -IDetour/Include -IDetourTileCache/Include  -IDetourCrowd/Include -IRecast/Include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -Wall -ffast-math -g -O2
  CXXFLAGS  += $(CFLAGS) -fno-exceptions -fno-rtti
  LDFLAGS   += 
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/DetourNavMeshQuery.o \
	$(OBJDIR)/DetourNode.o \
	$(OBJDIR)/DetourNavMesh.o \
	$(OBJDIR)/DetourNavMeshBuilder.o \
	$(OBJDIR)/DetourCommon.o \
	$(OBJDIR)/DetourAlloc.o \
	$(OBJDIR)/DetourObstacleAvoidance.o \
	$(OBJDIR)/DetourLocalBoundary.o \
	$(OBJDIR)/DetourProximityGrid.o \
	$(OBJDIR)/DetourPathCorridor.o \
	$(OBJDIR)/DetourCrowd.o \
	$(OBJDIR)/DetourPathQueue.o \
	$(OBJDIR)/DetourTileCache.o \
	$(OBJDIR)/DetourTileCacheBuilder.o \
	$(OBJDIR)/RecastLayers.o \
	$(OBJDIR)/RecastMesh.o \
	$(OBJDIR)/Recast.o \
	$(OBJDIR)/RecastRasterization.o \
	$(OBJDIR)/RecastAlloc.o \
	$(OBJDIR)/RecastMeshDetail.o \
	$(OBJDIR)/RecastFilter.o \
	$(OBJDIR)/RecastContour.o \
	$(OBJDIR)/RecastRegion.o \
	$(OBJDIR)/RecastArea.o \
	$(OBJDIR)/RecastDebugDraw.o \
	$(OBJDIR)/DetourDebugDraw.o \
	$(OBJDIR)/RecastDump.o \
	$(OBJDIR)/DebugDraw.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking RecastDetour
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning RecastDetour
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/DetourNavMeshQuery.o: Detour/Source/DetourNavMeshQuery.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DetourNode.o: Detour/Source/DetourNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DetourNavMesh.o: Detour/Source/DetourNavMesh.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DetourNavMeshBuilder.o: Detour/Source/DetourNavMeshBuilder.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DetourCommon.o: Detour/Source/DetourCommon.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DetourAlloc.o: Detour/Source/DetourAlloc.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DetourTileCache.o: DetourTileCache/Source/DetourTileCache.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DetourTileCacheBuilder.o: DetourTileCache/Source/DetourTileCacheBuilder.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DetourObstacleAvoidance.o: DetourCrowd/Source/DetourObstacleAvoidance.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DetourLocalBoundary.o: DetourCrowd/Source/DetourLocalBoundary.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DetourProximityGrid.o: DetourCrowd/Source/DetourProximityGrid.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DetourPathCorridor.o: DetourCrowd/Source/DetourPathCorridor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DetourCrowd.o: DetourCrowd/Source/DetourCrowd.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DetourPathQueue.o: DetourCrowd/Source/DetourPathQueue.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RecastLayers.o: Recast/Source/RecastLayers.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RecastMesh.o: Recast/Source/RecastMesh.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Recast.o: Recast/Source/Recast.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RecastRasterization.o: Recast/Source/RecastRasterization.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RecastAlloc.o: Recast/Source/RecastAlloc.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RecastMeshDetail.o: Recast/Source/RecastMeshDetail.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RecastFilter.o: Recast/Source/RecastFilter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RecastContour.o: Recast/Source/RecastContour.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RecastRegion.o: Recast/Source/RecastRegion.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RecastArea.o: Recast/Source/RecastArea.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RecastDebugDraw.o: DebugUtils/Source/RecastDebugDraw.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DetourDebugDraw.o: DebugUtils/Source/DetourDebugDraw.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RecastDump.o: DebugUtils/Source/RecastDump.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DebugDraw.o: DebugUtils/Source/DebugDraw.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
