-- Lua file generated by Blender class export script.
-- WARNING: If you modify this file, your changes will be lost if it is subsequently re-exported from blender

class `Tyre` (ColClass) {
    renderingDistance = 200.0;
    castShadows = true;
    placementZOffset = 0.20000000298023224;
    placementRandomRotation = false;
}

