-- Lua file generated by Blender class export script.
-- WARNING: If you modify this file, your changes will be lost if it is subsequently re-exported from blender

class `Brick` (ColClass) {
    renderingDistance = 15.0;
    castShadows = true;
    placementZOffset = 0.029999999329447746;
    placementRandomRotation = false;
}

class `WineBottle2` (ColClass) {
    renderingDistance = 10.0;
    castShadows = true;
    placementZOffset = 0.10508999973535538;
    placementRandomRotation = true;
    colMesh = `WineBottle.gcol`;
}

class `WineBottle1` (ColClass) {
    renderingDistance = 10.0;
    castShadows = true;
    placementZOffset = 0.10508999973535538;
    placementRandomRotation = true;
    colMesh = `WineBottle.gcol`;
}

class `Money` (ColClass) {
    renderingDistance = 50.0;
    castShadows = true;
    placementZOffset = 0.014999999664723873;
    placementRandomRotation = true;
}

class `PizzaBox` (ColClass) {
    renderingDistance = 50.0;
    castShadows = true;
    placementZOffset = 0.02500000037252903;
    placementRandomRotation = false;
}

