-- Lua file generated by Blender class export script.
-- WARNING: If you modify this file, your changes will be lost if it is subsequently re-exported from blender

class `Terrain` (ColClass) {
    renderingDistance = 1000.0;
    castShadows = false;
    placementZOffset = false;
    placementRandomRotation = false;
}

