-- Lua file generated by Blender class export script.
-- WARNING: If you modify this file, your changes will be lost if it is subsequently re-exported from blender

class `Simple2` (BaseClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = 1.0000009536743164;
    placementRandomRotation = false;
}

class `Simple` (BaseClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = 0.9999998807907104;
    placementRandomRotation = false;
}

