-- Lua file generated by Blender class export script.
-- WARNING: If you modify this file, your changes will be lost if it is subsequently re-exported from blender

class `Log2` (ColClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = false;
    placementRandomRotation = true;
}

class `Log1` (ColClass) {
    renderingDistance = 60.0;
    castShadows = true;
    placementZOffset = 0.30000001192092896;
    placementRandomRotation = true;
}

