-- Lua file generated by Blender class export script.
-- WARNING: If you modify this file, your changes will be lost if it is subsequently re-exported from blender

class `Wheel` (ColClass) {
    renderingDistance = 40.0;
    castShadows = true;
    placementZOffset = 0.30000001192092896;
    placementRandomRotation = false;
}

class `Body` (ColClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = 0.7300000190734863;
    placementRandomRotation = false;
}

