class "Track" (ColClass) {castShadows=true,renderingDistance=1200}

class "roadpiece001" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece002" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece003" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece004" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece005" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece006" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece007" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece008" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece009" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece010" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece011" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece012" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece013" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece014" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece015" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece016" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece017" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece018" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece019" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece020" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece021" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece022" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece023" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece024" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece025" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece026" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece027" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece028" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece029" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece030" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece031" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece032" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece033" (ColClass) {castShadows=false,renderingDistance=1200}
class "roadpiece034" (ColClass) {castShadows=false,renderingDistance=1200}