-- Lua file generated by Blender class export script.
-- WARNING: If you modify this file, your changes will be lost if it is subsequently re-exported from blender

class `Pin` (ColClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = 0.14800000190734863;
    placementRandomRotation = true;
}

class `Ball` (ColClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = 0.10000000149011612;
    placementRandomRotation = true;
}

