-- Lua file generated by Blender class export script.
-- WARNING: If you modify this file, your changes will be lost if it is subsequently re-exported from blender

class "Character" (ColClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = false;
    placementRandomRotation = false;
}

