-- Lua file generated by Blender class export script.
-- WARNING: If you modify this file, your changes will be lost if it is subsequently re-exported from blender

class `Long` (ColClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = 0.30000001192092896;
    placementRandomRotation = false;
}

class `Small` (ColClass) {
    renderingDistance = 30.0;
    castShadows = true;
    placementZOffset = 0.15000000596046448;
    placementRandomRotation = false;
}

class `Big` (ColClass) {
    renderingDistance = 70.0;
    castShadows = true;
    placementZOffset = 0.30000001192092896;
    placementRandomRotation = false;
}

