-- Lua file generated by Blender class export script.
-- WARNING: If you modify this file, your changes will be lost if it is subsequently re-exported from blender

class `JengaBrick` (ColClass) {
    renderingDistance = 50.0;
    castShadows = true;
    placementZOffset = 0.11999999731779099;
    placementRandomRotation = false;
}

