-- Lua file generated by Blender class export script.
-- WARNING: If you modify this file, your changes will be lost if it is subsequently re-exported from blender

class `Terrain` (ColClass) {
    renderingDistance = 1000.0;
    castShadows = false;
    placementZOffset = false;
    placementRandomRotation = false;
    gfxMesh = `meshes/Terrain.mesh`;
    colMesh = `meshes/Terrain.gcol`;
}

class `Cube` (ColClass) {
    renderingDistance = 25000.0;
    castShadows = true;
    placementZOffset = false;
    placementRandomRotation = false;
    gfxMesh = `meshes/Cube.mesh`;
    colMesh = `meshes/Cube.gcol`;
}
